"""Independent lexical-semantic analysis modules."""

from versevad.lexical_semantic.aoa import (
    AOA_CONTENT_WORD_POS,
    KUPERMAN_AOA_FILENAME,
    KUPERMAN_AOA_SHA256,
    AoAAnalysisResult,
    AoAConfiguration,
    AoAMatchMethod,
    AoAModule,
    AoAModuleError,
    attach_aoa_relationships,
)
from versevad.lexical_semantic.concreteness import (
    BRYSBAERT_CONCRETENESS_FILENAME,
    BRYSBAERT_CONCRETENESS_SHA256,
    ConcretenessAnalysisResult,
    ConcretenessConfiguration,
    ConcretenessMatchMethod,
    ConcretenessModule,
    ConcretenessModuleError,
)
from versevad.lexical_semantic.frequency import (
    CONTENT_WORD_POS,
    SUBTLEX_US_RELATIVE_PATH,
    SUBTLEX_US_SHA256,
    FrequencyAnalysisResult,
    FrequencyConfiguration,
    FrequencyMatchMethod,
    FrequencyModule,
    FrequencyModuleError,
)
from versevad.lexical_semantic.readability import (
    ReadabilityAnalysisResult,
    ReadabilityConfiguration,
    ReadabilityModule,
    ReadabilitySummary,
    ReadabilityWordAudit,
)
from versevad.lexical_semantic.sentiment import (
    VADER_CITATION,
    VaderScore,
    VaderSegmentScore,
    VaderSentimentAnalysisResult,
    VaderSentimentConfiguration,
    VaderSentimentModule,
)
from versevad.lexical_semantic.sensorimotor import (
    LANCASTER_SENSORIMOTOR_RELATIVE_PATH,
    LANCASTER_SENSORIMOTOR_SHA256,
    SENSORIMOTOR_DIMENSIONS,
    SensorimotorAnalysisResult,
    SensorimotorConfiguration,
    SensorimotorMatchMethod,
    SensorimotorModule,
    SensorimotorModuleError,
)

__all__ = [
    "AOA_CONTENT_WORD_POS",
    "BRYSBAERT_CONCRETENESS_FILENAME",
    "BRYSBAERT_CONCRETENESS_SHA256",
    "KUPERMAN_AOA_FILENAME",
    "KUPERMAN_AOA_SHA256",
    "LANCASTER_SENSORIMOTOR_RELATIVE_PATH",
    "LANCASTER_SENSORIMOTOR_SHA256",
    "AoAAnalysisResult",
    "AoAConfiguration",
    "AoAMatchMethod",
    "AoAModule",
    "AoAModuleError",
    "ConcretenessAnalysisResult",
    "ConcretenessConfiguration",
    "ConcretenessMatchMethod",
    "ConcretenessModule",
    "ConcretenessModuleError",
    "CONTENT_WORD_POS",
    "SUBTLEX_US_RELATIVE_PATH",
    "SUBTLEX_US_SHA256",
    "FrequencyAnalysisResult",
    "FrequencyConfiguration",
    "FrequencyMatchMethod",
    "FrequencyModule",
    "FrequencyModuleError",
    "ReadabilityAnalysisResult",
    "ReadabilityConfiguration",
    "ReadabilityModule",
    "ReadabilitySummary",
    "ReadabilityWordAudit",
    "SENSORIMOTOR_DIMENSIONS",
    "SensorimotorAnalysisResult",
    "SensorimotorConfiguration",
    "SensorimotorMatchMethod",
    "SensorimotorModule",
    "SensorimotorModuleError",
    "VADER_CITATION",
    "VaderScore",
    "VaderSegmentScore",
    "VaderSentimentAnalysisResult",
    "VaderSentimentConfiguration",
    "VaderSentimentModule",
    "attach_aoa_relationships",
]
